### ISSUE TITLE
Keskenjäänyt sähköpostiosoitteen vaihto aiheuttaa palvelinvirheen uudelleen vaihdettaessa

### ISSUE THREAD

**Issue by helihyv** [artoh/kitupiikki#1275]

**Comment by helihyv** [comment]
Jos Minä sivulla vaihtaa sähköpostiosoitetta ja painaa tallenna, mutta ei syötä saatua koodia, uusi shköpostiosoitteen vaihtoj ja tallennuksen painamine aiheuttaa  palvelinvirheen:
today at 11:51:14  error: duplicate key value violates unique constraint "confirmation_link_key"
today at 11:51:14      at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/dist/parser.js:287:98)
today at 11:51:14      at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/dist/parser.js:126:29)
today at 11:51:14      at Parser.parse (/usr/src/app/node_modules/pg-protocol/dist/parser.js:39:38)
today at 11:51:14      at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/dist/index.js:11:42)
today at 11:51:14      at Socket.emit (events.js:376:20)
today at 11:51:14      at addChunk (internal/streams/readable.js:309:12)
today at 11:51:14      at readableAddChunk (internal/streams/readable.js:284:9)
today at 11:51:14      at Socket.Readable.push (internal/streams/readable.js:223:10)
today at 11:51:14      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
today at 11:51:14  2023-01-13T09:51:14.004Z 500 PATCH /me - 964.820 Kitsas 4.0-beta.2
